name: argenis_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.3
  url_launcher: ^6.0.20
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.8
  mime_type: ^1.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  validators: ^3.0.0

flutter:


  uses-material-design: true


  assets:
    - images/assets/argenis.jpg
    - images/assets/fondoLogin.jpg
    - images/assets/fondo.jpg
    - images/assets/fondoPreview.gif
    - images/assets/Font.jpg
    - images/users/chikil.jpg
    - images/users/camarena.jpg
    - images/users/ayalax.jpg
    - images/assets/granos.gif
    - images/assets/image.jpg

